INSERT INTO Genres (Name) VALUES 
    ('Blues'),
    ('Disco'),
    ('Reggae'),
    ('Ambient'),
    ('Pop');
INSERT INTO Singers (Name) VALUES 
    ('Tom Waits'),
    ('Eric Clapton'),
    ('ABBA'),
    ('Bee Gees'),
    ('Bob Marley'),
    ('Matisyahu'),
    ('Aphex Twin'),
    ('Michael Jackson');
INSERT INTO Albums (Name, Year) VALUES 
    ('Closing Time', 1985),
    ('Slowhand', 1986),
    ('Ring Ring', 1980),
    ('Spicks and Specks', 1979),
    ('Soul Rebels', 1990),
    ('Light', 1995),
    ('Syro', 2018),
    ('King of Pop', 2007);
INSERT INTO Tracks (Name, Duration, Album_id) VALUES 
    ('Virginia Avenue', 165, (select id from albums where name = 'Closing Time')),
    ('Martha', 260, (select id from albums where name = 'Closing Time')),
    ('Cocaine', 365, (select id from albums where name = 'Slowhand')),
    ('Wonderful Tonight', 265, (select id from albums where name = 'Slowhand')),
    ('Ring Ring', 100, (select id from albums where name = 'Ring Ring')),
    ('Disillusion', 120, (select id from albums where name = 'Ring Ring')),
    ('How Many Birds', 240, (select id from albums where name = 'Spicks and Specks')),
    ('Playdown', 145, (select id from albums where name = 'Spicks and Specks')),
    ('Soul Rebels', 255, (select id from albums where name = 'Soul Rebels')),
    ('Try Me', 330, (select id from albums where name = 'Soul Rebels')),
    ('Smash Lies', 156, (select id from albums where name = 'Light')),
    ('We Will Walk', 286, (select id from albums where name = 'Light')),
    ('XMAS_EVET10', 145, (select id from albums where name = 'Syro')),
    ('My produkt 29', 147, (select id from albums where name = 'Syro')),
    ('Break Of Dawn', 295, (select id from albums where name = 'King of Pop'));
INSERT INTO Collections (Name, Year) VALUES 
    ('Collection 1', 2015),
    ('Collection 2', 2016),
    ('Collection 3', 2017),
    ('Collection 4', 2018),
    ('Collection 5', 2019),
    ('Collection 6', 2020),
    ('Collection 7', 2021),
    ('Collection 8', 2010);
INSERT INTO GenreSinger (Genre_id, Singer_id) VALUES 
    ((select id from genres where name = 'Blues'), (select id from singers where name = 'Tom Waits')),
    ((select id from genres where name = 'Blues'), (select id from singers where name = 'Eric Clapton')),
    ((select id from genres where name = 'Disco'), (select id from singers where name = 'ABBA')),
    ((select id from genres where name = 'Disco'), (select id from singers where name = 'Bee Gees')),
    ((select id from genres where name = 'Reggae'), (select id from singers where name = 'Bob Marley')),
    ((select id from genres where name = 'Reggae'), (select id from singers where name = 'Matisyahu')),
    ((select id from genres where name = 'Ambient'), (select id from singers where name = 'Aphex Twin')),
    ((select id from genres where name = 'Pop'), (select id from singers where name = 'Michael Jackson'));
INSERT INTO singeralbum (singer_id, album_id) VALUES 
    ((select id from singers where name = 'Tom Waits'), (select id from albums where name = 'Closing Time')),
    ((select id from singers where name = 'Eric Clapton'), (select id from albums where name = 'Slowhand')),
    ((select id from singers where name = 'ABBA'), (select id from albums where name = 'Ring Ring')),
    ((select id from singers where name = 'Bee Gees'), (select id from albums where name = 'Spicks and Specks')),
    ((select id from singers where name = 'Bob Marley'), (select id from albums where name = 'Soul Rebels')),
    ((select id from singers where name = 'Matisyahu'), (select id from albums where name = 'Light')),
    ((select id from singers where name = 'Aphex Twin'), (select id from albums where name = 'Syro')),
    ((select id from singers where name = 'Michael Jackson'), (select id from albums where name = 'King of Pop'));
INSERT INTO trackcollection (track_id, collection_id) VALUES 
    ((select id from tracks where name = 'Virginia Avenue'), (select id from collections where name = 'Collection 1')),
    ((select id from tracks where name = 'Martha'), (select id from collections where name = 'Collection 1')),
    ((select id from tracks where name = 'Cocaine'), (select id from collections where name = 'Collection 2')),
    ((select id from tracks where name = 'Wonderful Tonight'), (select id from collections where name = 'Collection 2')),
    ((select id from tracks where name = 'Ring Ring'), (select id from collections where name = 'Collection 3')),
    ((select id from tracks where name = 'Disillusion'), (select id from collections where name = 'Collection 3')),
    ((select id from tracks where name = 'Virginia Avenue'), (select id from collections where name = 'Collection 8')),
    ((select id from tracks where name = 'Martha'), (select id from collections where name = 'Collection 8')),
    ((select id from tracks where name = 'Cocaine'), (select id from collections where name = 'Collection 8')),
    ((select id from tracks where name = 'Wonderful Tonight'), (select id from collections where name = 'Collection 8')),
    ((select id from tracks where name = 'Ring Ring'), (select id from collections where name = 'Collection 8')),
    ((select id from tracks where name = 'Disillusion'), (select id from collections where name = 'Collection 8')),
    ((select id from tracks where name = 'How Many Birds'), (select id from collections where name = 'Collection 4')),
    ((select id from tracks where name = 'Playdown'), (select id from collections where name = 'Collection 4')),
    ((select id from tracks where name = 'How Many Birds'), (select id from collections where name = 'Collection 1')),
    ((select id from tracks where name = 'Playdown'), (select id from collections where name = 'Collection 1')),
    ((select id from tracks where name = 'Soul Rebels'), (select id from collections where name = 'Collection 5')),
    ((select id from tracks where name = 'Try Me'), (select id from collections where name = 'Collection 5')),
    ((select id from tracks where name = 'Soul Rebels'), (select id from collections where name = 'Collection 6')),
    ((select id from tracks where name = 'Try Me'), (select id from collections where name = 'Collection 6')),
    ((select id from tracks where name = 'Smash Lies'), (select id from collections where name = 'Collection 6')),
    ((select id from tracks where name = 'We Will Walk'), (select id from collections where name = 'Collection 6')),
    ((select id from tracks where name = 'XMAS_EVET10'), (select id from collections where name = 'Collection 7')),
    ((select id from tracks where name = 'My produkt 29'), (select id from collections where name = 'Collection 7')),
    ((select id from tracks where name = 'Break Of Dawn'), (select id from collections where name = 'Collection 7')),
    ((select id from tracks where name = 'Break Of Dawn'), (select id from collections where name = 'Collection 8'));
